//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codeer.LowCode.Bindings.ApexCharts.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Codeer.LowCode.Bindings.ApexCharts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_Area {
            get {
                return ResourceManager.GetString("SeriesType_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_Bar {
            get {
                return ResourceManager.GetString("SeriesType_Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Donut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_Donut {
            get {
                return ResourceManager.GetString("SeriesType_Donut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Heatmap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_Heatmap {
            get {
                return ResourceManager.GetString("SeriesType_Heatmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_Line {
            get {
                return ResourceManager.GetString("SeriesType_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pie に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_Pie {
            get {
                return ResourceManager.GetString("SeriesType_Pie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PolarArea に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_PolarArea {
            get {
                return ResourceManager.GetString("SeriesType_PolarArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Radar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_Radar {
            get {
                return ResourceManager.GetString("SeriesType_Radar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RadialBar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_RadialBar {
            get {
                return ResourceManager.GetString("SeriesType_RadialBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RangeArea に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_RangeArea {
            get {
                return ResourceManager.GetString("SeriesType_RangeArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scatter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_Scatter {
            get {
                return ResourceManager.GetString("SeriesType_Scatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Treemap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_Treemap {
            get {
                return ResourceManager.GetString("SeriesType_Treemap", resourceCulture);
            }
        }
        internal static string ApexChartField {
            get {
                return ResourceManager.GetString("ApexChartField", resourceCulture);
            }
        }

        internal static string ApexHBarChartField {
            get {
                return ResourceManager.GetString("ApexHBarChartField", resourceCulture);
            }
        }

        internal static string ApexRadialChartField {
            get {
                return ResourceManager.GetString("ApexRadialChartField", resourceCulture);
            }
        }

        internal static string SearchCondition {
            get {
                return ResourceManager.GetString("SearchCondition", resourceCulture);
            }
        }

        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }

        internal static string CategoryField {
            get {
                return ResourceManager.GetString("CategoryField", resourceCulture);
            }
        }

        internal static string CategoryFormat {
            get {
                return ResourceManager.GetString("CategoryFormat", resourceCulture);
            }
        }

        internal static string SeriesFractionDigits {
            get {
                return ResourceManager.GetString("SeriesFractionDigits", resourceCulture);
            }
        }

        internal static string ShowLegend {
            get {
                return ResourceManager.GetString("ShowLegend", resourceCulture);
            }
        }

        internal static string SeriesType {
            get {
                return ResourceManager.GetString("SeriesType", resourceCulture);
            }
        }

        internal static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }

        internal static string SeriesField {
            get {
                return ResourceManager.GetString("SeriesField", resourceCulture);
            }
        }

        internal static string FullWidthBar {
            get {
                return ResourceManager.GetString("FullWidthBar", resourceCulture);
            }
        }

        internal static string ShowXAxisGrid {
            get {
                return ResourceManager.GetString("ShowXAxisGrid", resourceCulture);
            }
        }

        internal static string ShowYAxisGrid {
            get {
                return ResourceManager.GetString("ShowYAxisGrid", resourceCulture);
            }
        }

        internal static string CategoryBar {
            get {
                return ResourceManager.GetString("CategoryBar", resourceCulture);
            }
        }

        internal static string CategoryGrid {
            get {
                return ResourceManager.GetString("CategoryGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aggregate chart に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApexAggregateChartField {
            get {
                return ResourceManager.GetString("ApexAggregateChartField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aggregate horizontal bar chart に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApexAggregateHBarChartField {
            get {
                return ResourceManager.GetString("ApexAggregateHBarChartField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aggregate pie chart に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApexAggregateRadialChartField {
            get {
                return ResourceManager.GetString("ApexAggregateRadialChartField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ApexCharts - Aggregate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CategoryAggregate {
            get {
                return ResourceManager.GetString("CategoryAggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group dates by に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CategoryDateUnit {
            get {
                return ResourceManager.GetString("CategoryDateUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fiscal year start month に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FiscalYearStartMonth {
            get {
                return ResourceManager.GetString("FiscalYearStartMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Category order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CategoryOrder {
            get {
                return ResourceManager.GetString("CategoryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Category limit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CategoryLimit {
            get {
                return ResourceManager.GetString("CategoryLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Split series by に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesGroupField {
            get {
                return ResourceManager.GetString("SeriesGroupField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aggregate function に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesFunction {
            get {
                return ResourceManager.GetString("SeriesFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChartAggregateFunction_Sum {
            get {
                return ResourceManager.GetString("ChartAggregateFunction_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChartAggregateFunction_Count {
            get {
                return ResourceManager.GetString("ChartAggregateFunction_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Average に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChartAggregateFunction_Avg {
            get {
                return ResourceManager.GetString("ChartAggregateFunction_Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChartAggregateFunction_Min {
            get {
                return ResourceManager.GetString("ChartAggregateFunction_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChartAggregateFunction_Max {
            get {
                return ResourceManager.GetString("ChartAggregateFunction_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distinct count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Function_CountDistinct {
            get {
                return ResourceManager.GetString("Function_CountDistinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (None) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChartDateUnit_None {
            get {
                return ResourceManager.GetString("ChartDateUnit_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Year に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChartDateUnit_Year {
            get {
                return ResourceManager.GetString("ChartDateUnit_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quarter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChartDateUnit_Quarter {
            get {
                return ResourceManager.GetString("ChartDateUnit_Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Month に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChartDateUnit_Month {
            get {
                return ResourceManager.GetString("ChartDateUnit_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Week に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChartDateUnit_Week {
            get {
                return ResourceManager.GetString("ChartDateUnit_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Day に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChartDateUnit_Day {
            get {
                return ResourceManager.GetString("ChartDateUnit_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hour に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChartDateUnit_Hour {
            get {
                return ResourceManager.GetString("ChartDateUnit_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChartCategoryOrder_Field {
            get {
                return ResourceManager.GetString("ChartCategoryOrder_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value (descending) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChartCategoryOrder_ValueDescending {
            get {
                return ResourceManager.GetString("ChartCategoryOrder_ValueDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value (ascending) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChartCategoryOrder_ValueAscending {
            get {
                return ResourceManager.GetString("ChartCategoryOrder_ValueAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set the category field. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Check_NoCategory {
            get {
                return ResourceManager.GetString("Check_NoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add at least one series. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Check_NoSeries {
            get {
                return ResourceManager.GetString("Check_NoSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   "Group dates by" can only be used for a date or date-time field ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Check_DateUnitRequiresDate {
            get {
                return ResourceManager.GetString("Check_DateUnitRequiresDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} cannot be used for {1}. Use a number field (Count needs no field). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Check_InvalidFunction {
            get {
                return ResourceManager.GetString("Check_InvalidFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Heatmap series and non-heatmap series cannot be mixed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Check_HeatmapCannotBeMixed {
            get {
                return ResourceManager.GetString("Check_HeatmapCannotBeMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (blank) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Blank {
            get {
                return ResourceManager.GetString("Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Displayed by Show in a script. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScriptOnly {
            get {
                return ResourceManager.GetString("ScriptOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow users to customize the aggregation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanCustomize {
            get {
                return ResourceManager.GetString("CanCustomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customize aggregation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset to design に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResetToDesign {
            get {
                return ResourceManager.GetString("ResetToDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (none) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesTitle {
            get {
                return ResourceManager.GetString("SeriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field {0} does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Check_UnknownField {
            get {
                return ResourceManager.GetString("Check_UnknownField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only modules that have a table can be aggregated (modules defined by a QueryField or without a table cannot be used): {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Check_NotTableModule {
            get {
                return ResourceManager.GetString("Check_NotTableModule", resourceCulture);
            }
        }
    }
}
