//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codeer.LowCode.Bindings.ApexCharts.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Codeer.LowCode.Bindings.ApexCharts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_Area {
            get {
                return ResourceManager.GetString("SeriesType_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_Bar {
            get {
                return ResourceManager.GetString("SeriesType_Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Donut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_Donut {
            get {
                return ResourceManager.GetString("SeriesType_Donut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Heatmap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_Heatmap {
            get {
                return ResourceManager.GetString("SeriesType_Heatmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_Line {
            get {
                return ResourceManager.GetString("SeriesType_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pie に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_Pie {
            get {
                return ResourceManager.GetString("SeriesType_Pie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PolarArea に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_PolarArea {
            get {
                return ResourceManager.GetString("SeriesType_PolarArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Radar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_Radar {
            get {
                return ResourceManager.GetString("SeriesType_Radar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RadialBar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_RadialBar {
            get {
                return ResourceManager.GetString("SeriesType_RadialBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RangeArea に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_RangeArea {
            get {
                return ResourceManager.GetString("SeriesType_RangeArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scatter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_Scatter {
            get {
                return ResourceManager.GetString("SeriesType_Scatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Treemap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeriesType_Treemap {
            get {
                return ResourceManager.GetString("SeriesType_Treemap", resourceCulture);
            }
        }
        internal static string ApexChartField {
            get {
                return ResourceManager.GetString("ApexChartField", resourceCulture);
            }
        }

        internal static string ApexHBarChartField {
            get {
                return ResourceManager.GetString("ApexHBarChartField", resourceCulture);
            }
        }

        internal static string ApexRadialChartField {
            get {
                return ResourceManager.GetString("ApexRadialChartField", resourceCulture);
            }
        }

        internal static string SearchCondition {
            get {
                return ResourceManager.GetString("SearchCondition", resourceCulture);
            }
        }

        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }

        internal static string CategoryField {
            get {
                return ResourceManager.GetString("CategoryField", resourceCulture);
            }
        }

        internal static string CategoryFormat {
            get {
                return ResourceManager.GetString("CategoryFormat", resourceCulture);
            }
        }

        internal static string SeriesFractionDigits {
            get {
                return ResourceManager.GetString("SeriesFractionDigits", resourceCulture);
            }
        }

        internal static string ShowLegend {
            get {
                return ResourceManager.GetString("ShowLegend", resourceCulture);
            }
        }

        internal static string SeriesType {
            get {
                return ResourceManager.GetString("SeriesType", resourceCulture);
            }
        }

        internal static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }

        internal static string SeriesField {
            get {
                return ResourceManager.GetString("SeriesField", resourceCulture);
            }
        }

        internal static string FullWidthBar {
            get {
                return ResourceManager.GetString("FullWidthBar", resourceCulture);
            }
        }

        internal static string ShowXAxisGrid {
            get {
                return ResourceManager.GetString("ShowXAxisGrid", resourceCulture);
            }
        }

        internal static string ShowYAxisGrid {
            get {
                return ResourceManager.GetString("ShowYAxisGrid", resourceCulture);
            }
        }

        internal static string CategoryBar {
            get {
                return ResourceManager.GetString("CategoryBar", resourceCulture);
            }
        }

        internal static string CategoryGrid {
            get {
                return ResourceManager.GetString("CategoryGrid", resourceCulture);
            }
        }

    }
}
